# Generated by Django 6.0.5 on 2026-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='availability',
            field=models.CharField(default='Morning', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='mode',
            field=models.CharField(default='Morning', max_length=50),
            preserve_default=False,
        ),
    ]
