# Generated by Django 6.0.5 on 2026-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutor_availability_tutor_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='area',
            field=models.CharField(default='Raipur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='city',
            field=models.CharField(default='Tikrapara', max_length=100),
            preserve_default=False,
        ),
    ]
